# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-11 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myyxj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineBtns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=100)),
                ('bref_url', models.CharField(max_length=255, null=True)),
                ('is_used', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '首页',
            },
        ),
    ]
