# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-13 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myyxj', '0002_minebtns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minebtns',
            options={'verbose_name': '商品分类'},
        ),
        migrations.RenameField(
            model_name='minebtns',
            old_name='class_name',
            new_name='twotype_name',
        ),
        migrations.RenameField(
            model_name='minebtns',
            old_name='btn',
            new_name='typename',
        ),
        migrations.RemoveField(
            model_name='minebtns',
            name='bref_url',
        ),
        migrations.RemoveField(
            model_name='minebtns',
            name='is_used',
        ),
        migrations.AlterModelTable(
            name='minebtns',
            table='yxj_goodstype',
        ),
    ]
