# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-06 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaxf', '0009_minebtns'),
    ]

    operations = [
        migrations.AddField(
            model_name='minebtns',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
    ]
